### ISSUE TITLE
[RBAC] Provide useful error feedback

### ISSUE THREAD

**Issue by IniZio** [oursky/skygear-rbac#20]
## Tasks

- [ ] Validate request params and return error if not accepted e.g. empty subject
- [ ] Add logging
  - [ ] Request params
  - [ ] Enforcer errors e.g. Invalid policy format in persist storage
- [ ] Return updated result for e.g. role assignments
